# Generated by Django 5.0.2 on 2025-05-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='skill',
        ),
        migrations.AddField(
            model_name='progress',
            name='time_spent',
            field=models.IntegerField(default=0, help_text='Time spent in minutes'),
        ),
        migrations.AddField(
            model_name='resource',
            name='estimated_time',
            field=models.IntegerField(default=1, help_text='Estimated time in hours'),
        ),
        migrations.AddField(
            model_name='resource',
            name='prerequisites',
            field=models.ManyToManyField(related_name='required_resources', to='roadmap.skill'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='learning_style',
            field=models.CharField(choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('reading', 'Reading'), ('kinesthetic', 'Kinesthetic')], default='visual', max_length=50),
        ),
        migrations.AddField(
            model_name='roadmapskill',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadmapskill',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='learning_resources',
            field=models.ManyToManyField(blank=True, to='roadmap.resource'),
        ),
        migrations.AddField(
            model_name='skill',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='dependent_skills', to='roadmap.skill'),
        ),
    ]
