# Generated by Django 5.0.2 on 2025-05-14 19:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_remove_resource_skill_progress_time_spent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='roadmap',
            old_name='skills',
            new_name='target_skills',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='current_skill_level',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='learning_style',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='target_completion_time',
        ),
        migrations.RemoveField(
            model_name='roadmapskill',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='roadmapskill',
            name='estimated_completion_time',
        ),
        migrations.RemoveField(
            model_name='roadmapskill',
            name='start_date',
        ),
        migrations.AddField(
            model_name='roadmap',
            name='current_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='preferred_resources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='target_level',
            field=models.CharField(choices=[('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='timeline',
            field=models.IntegerField(default=1, help_text='Timeline in months'),
        ),
        migrations.AddField(
            model_name='roadmapskill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadmapskill',
            name='notes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='roadmapskill',
            name='resources',
            field=models.ManyToManyField(to='roadmap.resource'),
        ),
        migrations.AddField(
            model_name='roadmapskill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roadmapskill',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_goals', models.TextField()),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
