# Generated by Django 5.0.2 on 2025-05-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0005_add_fields_and_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmap',
            name='preferred_resources',
        ),
    ]
