# Generated by Django 5.0.2 on 2025-05-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0006_remove_roadmap_preferred_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='preferred_resources',
            field=models.ManyToManyField(blank=True, to='roadmap.resource'),
        ),
    ]
