# Generated by Django 5.0.2 on 2025-05-17 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0007_roadmap_preferred_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField(help_text='List of options for MCQ')),
                ('correct_answer', models.IntegerField(help_text='Index of the correct option in options list')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='roadmap.skill')),
            ],
        ),
    ]
