# Generated by Django 5.0.2 on 2025-05-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0008_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
