# Generated by Django 5.0.2 on 2025-05-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0009_delete_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='current_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('master', 'Master')], max_length=20),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='target_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('master', 'Master')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('master', 'Master')], max_length=20),
        ),
    ]
