# Generated by Django 5.0.2 on 2025-05-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0010_alter_roadmap_current_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
