# Generated by Django 5.0.2 on 2025-05-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0011_roadmap_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Master')]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Master')]),
        ),
    ]
