# Generated by Django 5.0.2 on 2025-05-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0012_alter_resource_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='hours_per_week',
            field=models.IntegerField(default=5, help_text='Hours per week user plans to study'),
        ),
    ]
